version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - ./apps/api:/app
    networks:
      - space-sa

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api
    volumes:
      - ./apps/web:/app
    networks:
      - space-sa

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - space-sa

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=space_sa
      - POSTGRES_USER=space_sa
      - POSTGRES_PASSWORD=space_sa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - space-sa

volumes:
  redis_data:
  postgres_data:

networks:
  space-sa:
    driver: bridge
