/**
 * TypeScript type definitions for the EyeWitness satellite monitoring application
 */

/**
 * Represents a satellite being tracked by our monitoring system
 */
export interface Satellite {
  /** Unique identifier for the satellite within our system */
  id: string;
  /** Human-readable name of the satellite (e.g., "ISS", "Hubble") */
  name: string;
  /** Altitude in kilometers above Earth's surface */
  altitudeKm: number;
  /** Orbital inclination in degrees (0° = equatorial, 90° = polar) */
  inclinationDeg: number;
  /** Right Ascension of Ascending Node in degrees (orbital orientation) */
  raanDeg: number;
}

/**
 * Represents a close approach (conjunction) between two space objects
 */
export interface ConjunctionEvent {
  /** Time of Closest Approach - when the objects will be nearest */
  tca: string;
  /** Predicted miss distance in kilometers */
  missDistanceKm: number;
  /** Name or ID of the first object in the conjunction */
  objectA: string;
  /** Name or ID of the second object in the conjunction */
  objectB: string;
  /** Altitude in kilometers where the conjunction occurs */
  altitudeKm: number;
}

/**
 * Represents space weather data from NOAA SWPC
 */
export interface SpaceWeatherData {
  /** ISO timestamp of the measurement */
  time: string;
  /** Kp index value (0-9 scale) measuring geomagnetic activity */
  kp: number;
}

/**
 * Represents a risk alert generated by our monitoring system
 */
export interface RiskAlert {
  /** Unique identifier for this risk alert */
  id: string;
  /** Type of risk: conjunction (close approach) or space_weather (solar activity) */
  type: 'conjunction' | 'space_weather';
  /** Severity level: Low (monitor), Medium (prepare), High (act now) */
  severity: 'Low' | 'Medium' | 'High';
  /** Name of the satellite affected (optional for space weather alerts) */
  satellite?: string;
  /** Human-readable message describing the risk */
  message: string;
  /** Suggested action for operators to take */
  suggestedAction: string;
  /** ISO timestamp of when the alert was generated */
  timestamp: string;
  /** Whether the alert has been executed by an operator */
  acknowledged: boolean;
}

/**
 * Represents a satellite option for the dropdown menu
 */
export interface SatelliteOption {
  /** Human-readable name of the satellite */
  name: string;
  /** Altitude in kilometers above Earth's surface */
  altitudeKm: number;
  /** Orbital inclination in degrees */
  inclinationDeg: number;
  /** Right Ascension of Ascending Node in degrees */
  raanDeg: number;
}